name: C/C++ CI
name: C/C++ CI on ${{ matrix.os }}

on: [push]

jobs:
  build:
    name: C/C++ CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: make clean
      run: make clean
    - name: make
      run: make
    
