name: C/C++ CI

on: [push]

jobs:
  build:
    name: C/C++ CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: make clean
      run: make clean
    - name: make
      run: make
#     - name: Upload to Release
#       uses: JasonEtco/upload-to-release@v0.1.1
    
